"""MOD-LSE (2026-05-03) — Litigation Strategy and Escalation Planner tests.

Covers the strategy planner end to end:

- ``litigation_strategy`` is a supported recommendation type.
- Strategy retrieval query expansion includes escalation terms.
- Successful generation persists a strategy_payload_json + ``review_required=True``.
- Zero verified citations refuses with 422 (fail-closed).
- Missing facts surface in payload + are not invented.
- SC routes only when legally plausible (forum_level gate).
- Forbidden-phrase structural assertion blocks outcome promises.
- Tenant isolation: a strategy generated by tenant A is invisible to tenant B.
- Audit event written.
"""
from __future__ import annotations

import datetime
import hashlib
import json
from collections.abc import Iterable

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import select

from caseops_api.db.models import (
    AuditEvent,
    AuthorityDocument,
    AuthorityDocumentChunk,
    AuthorityDocumentType,
    ModelRun,
    Recommendation,
)
from caseops_api.db.session import get_session_factory
from caseops_api.schemas.litigation_strategy import (
    FORBIDDEN_OUTCOME_PHRASES,
    LitigationStrategyPayload,
    StrategyRoute,
    assert_no_forbidden_phrases,
)
from tests.test_auth_company import auth_headers, bootstrap_company

# ---------------------------------------------------------------
# Test helpers — seed a matter + authority, install a mock provider
# that returns a valid LitigationStrategyPayload-shaped JSON.
# ---------------------------------------------------------------


def _seed_authorities(records: Iterable[dict]) -> None:
    factory = get_session_factory()
    with factory() as session:
        for record in records:
            canonical = hashlib.sha256(
                (record["title"] + "|" + (record.get("case_reference") or "")).encode(
                    "utf-8"
                )
            ).hexdigest()[:40]
            doc = AuthorityDocument(
                title=record["title"],
                court_name=record["court_name"],
                forum_level=record["forum_level"],
                document_type=AuthorityDocumentType(record["document_type"]),
                decision_date=record["decision_date"],
                case_reference=record.get("case_reference"),
                summary=record.get("summary", ""),
                source=record.get("source", "manual"),
                adapter_name=record.get("adapter_name", "manual-seed"),
                source_reference=record.get("source_reference"),
                canonical_key=record.get("canonical_key", canonical),
                document_text=record["document_text"],
                extracted_char_count=len(record["document_text"]),
                ingested_at=datetime.datetime.now(datetime.UTC),
            )
            session.add(doc)
            session.flush()
            session.add(
                AuthorityDocumentChunk(
                    authority_document_id=doc.id,
                    chunk_index=0,
                    content=record["document_text"],
                )
            )
        session.commit()


def _seed_relevant_authority() -> str:
    """Seed a single SC authority that grounds an Article 136 SLP route.

    Returns the citation identifier the model should reference.
    """
    title = "Sushila Aggarwal v. State of NCT of Delhi (2020)"
    _seed_authorities(
        [
            {
                "title": title,
                "court_name": "Supreme Court of India",
                "forum_level": "supreme_court",
                "document_type": "judgment",
                "decision_date": datetime.date(2020, 1, 29),
                "case_reference": title,
                "summary": (
                    "Five-judge Constitution Bench held that anticipatory bail "
                    "under Section 438 CrPC is not time-limited; protection "
                    "subsists till the end of trial."
                ),
                "document_text": (
                    "The Constitution Bench of the Supreme Court held in Sushila "
                    "Aggarwal that anticipatory bail granted under Section 438 "
                    "of the Code of Criminal Procedure is not, as a matter of "
                    "law, time-limited. The Court further held that the "
                    "protection under Article 136 enables review of the High "
                    "Court order on substantial questions of law."
                ),
            }
        ]
    )
    return title


def _setup_matter(client: TestClient, *, forum_level: str = "high_court") -> tuple[str, str, str]:
    bootstrap_payload = bootstrap_company(client)
    token = str(bootstrap_payload["access_token"])
    company_slug = str(bootstrap_payload["company"]["slug"])
    matter = client.post(
        "/api/matters/",
        headers=auth_headers(token),
        json={
            "title": "Quashing of FIR and prospective SLP if denied",
            "matter_code": f"LSE-2026-{forum_level}",
            "practice_area": "criminal",
            "forum_level": forum_level,
            "court_name": "Delhi High Court",
            "client_name": "Test Petitioner",
            "opposing_party": "State of NCT of Delhi",
            "description": (
                "FIR registered under BNS s.318 + s.351. Petitioner seeks "
                "quashing under BNSS s.528. If the HC declines, the next "
                "route is an Article 136 SLP to the Supreme Court."
            ),
            "status": "active",
        },
    )
    assert matter.status_code == 200, matter.text
    return token, company_slug, str(matter.json()["id"])


def _valid_strategy_payload(citation: str) -> dict:
    """A grounded, forbidden-phrase-clean strategy payload the LLM
    schema accepts. Mirrors the LLM ``_LLMStrategyResponse`` shape."""
    return {
        "title": "Quashing route at HC, escalation to SC if dismissed",
        "current_posture": (
            "Matter is at the High Court stage with an FIR registered under "
            "BNS s.318 + s.351. The petitioner has filed for quashing under "
            "BNSS s.528."
        ),
        "recommended_route": {
            "label": "Quashing under BNSS s.528 + escalate via Article 136 SLP if HC dismisses",
            "rationale": (
                "The HC's inherent powers under BNSS s.528 cover this fact "
                "pattern. If quashing is declined, the next forum is the SC "
                "via Article 136 SLP, which entertains substantial questions "
                "from HC criminal-side orders."
            ),
            "confidence": "medium",
            "availability": "available",
            "supporting_citations": [f"[1] {citation}"],
            "risk_notes": (
                "Quashing is discretionary; outcome depends on the HC's "
                "assessment of bona fides."
            ),
        },
        "alternative_routes": [
            {
                "label": "Settle and file compromise petition",
                "rationale": "Compromise framework under BNSS s.359 / Gian Singh.",
                "confidence": "low",
                "availability": "uncertain",
                "supporting_citations": [f"[1] {citation}"],
                "risk_notes": None,
            }
        ],
        "forum_sequence": [
            {
                "forum_level": "high_court_single_bench",
                "stage_label": "Quashing petition",
                "forum_name": "Delhi High Court",
                "rationale": "HC inherent powers under BNSS s.528.",
                "statutory_basis": ["BNSS s.528"],
                "expected_filings": [
                    "quashing_petition", "vakalatnama", "affidavit",
                ],
            },
            {
                "forum_level": "supreme_court",
                "stage_label": "SLP if HC declines",
                "forum_name": "Supreme Court of India",
                "rationale": (
                    "Article 136 SLP grounds — substantial question on the "
                    "HC's exercise of inherent powers."
                ),
                "statutory_basis": ["Constitution Article 136"],
                "expected_filings": [
                    "special_leave_petition", "synopsis_list_of_dates",
                    "condonation_of_delay",
                ],
            },
        ],
        "limitation_flags": [
            {
                "label": "SLP filing window",
                "description": (
                    "Article 132 of the Limitation Act prescribes 60 days "
                    "for criminal SLPs. Date of HC dismissal is not yet on "
                    "file."
                ),
                "statutory_basis": "Limitation Act 1963 Article 132",
                "deadline_iso": None,
                "severity": "warning",
            }
        ],
        "required_documents": [
            "Certified copy of FIR",
            "Certified copy of HC quashing petition",
        ],
        "missing_facts": [
            "Date of HC dismissal (not yet pronounced)",
            "Whether complainant has consented to quashing",
        ],
        "risks": [
            {
                "label": "Cost of escalation",
                "description": (
                    "SLP-stage costs (court fee, senior counsel) are "
                    "material. The petitioner should budget accordingly."
                ),
                "severity": "medium",
                "mitigation": "Estimate at outset; secure client mandate.",
            }
        ],
        "next_best_actions": [
            "Wait for HC pronouncement",
            "If dismissed, prepare SLP within 60 days",
        ],
        "rationale": (
            "Two-stage strategy: pursue quashing at HC; if declined, "
            "escalate via SLP. Both routes rest on the same authorities."
        ),
        "confidence": "medium",
        "next_action": "Await HC listing; serve notice on State counsel.",
        "assumptions": ["FIR is the sole impugned proceeding."],
        "disclaimer": (
            "This strategy is a citation-grounded starting point and "
            "requires lawyer review before any filing."
        ),
    }


@pytest.fixture
def mock_strategy_provider(monkeypatch):
    """Install an LLM provider that always returns the valid payload."""
    from caseops_api.services.llm import LLMCompletion, LLMMessage

    citation = _seed_relevant_authority()
    payload = _valid_strategy_payload(citation)

    class _GoodProvider:
        name = "mock"
        model = "mock-strategy"

        def generate(self, messages: list[LLMMessage], **_kwargs):
            return LLMCompletion(
                text=json.dumps(payload),
                provider=self.name,
                model=self.model,
                prompt_tokens=120,
                completion_tokens=350,
                latency_ms=8,
            )

    # Patch BOTH the recommendations build_provider (used as fallback)
    # AND the strategy build_provider so the test does not depend on a
    # real LLM key.
    monkeypatch.setattr(
        "caseops_api.services.recommendations.build_provider",
        lambda *a, **kw: _GoodProvider(),
    )
    monkeypatch.setattr(
        "caseops_api.services.litigation_strategy.build_provider",
        lambda *a, **kw: _GoodProvider(),
    )
    return citation


# ---------------------------------------------------------------
# Type registration + retrieval-query expansion.
# ---------------------------------------------------------------


def test_litigation_strategy_is_a_supported_recommendation_type() -> None:
    from caseops_api.services.recommendations import SUPPORTED_TYPES

    assert "litigation_strategy" in SUPPORTED_TYPES


def test_strategy_retrieval_query_expansion_includes_escalation_terms() -> None:
    from caseops_api.db.models import Matter
    from caseops_api.services.recommendations import _build_retrieval_query

    fake = Matter(
        company_id="t",
        matter_code="X",
        title="Quashing of FIR",
        practice_area="criminal",
        forum_level="high_court",
        description="FIR under BNS s.318",
    )
    query = _build_retrieval_query(fake, "litigation_strategy")
    # Strategy retrieval needs escalation-ladder vocabulary or it
    # collapses to the practice-area facts and misses procedural
    # authorities.
    for needle in (
        "litigation strategy", "escalation", "Article 136",
        "Article 137", "limitation", "interim",
    ):
        assert needle in query, f"missing {needle!r} in expanded query"


# ---------------------------------------------------------------
# Forbidden-phrase scan — both as a unit and via persistence.
# ---------------------------------------------------------------


def test_assert_no_forbidden_phrases_blocks_outcome_promises() -> None:
    """Every entry in FORBIDDEN_OUTCOME_PHRASES must be rejected — case-
    insensitive, anywhere in the string. This is the structural test
    the PRD §2 hard rule depends on."""
    for phrase in FORBIDDEN_OUTCOME_PHRASES:
        with pytest.raises(ValueError, match=phrase):
            assert_no_forbidden_phrases(
                f"This route is a {phrase} — file immediately."
            )
        # Case-insensitive — the production scan lowercases.
        with pytest.raises(ValueError):
            assert_no_forbidden_phrases(phrase.upper())


def test_assert_no_forbidden_phrases_passes_clean_text() -> None:
    assert_no_forbidden_phrases(
        "The petitioner has a credible route. Lawyer review is required."
    )


def test_strategy_test_fixture_has_no_forbidden_phrases() -> None:
    """Self-check on the test fixture — if this ever fails, fix the
    fixture rather than the assertion."""
    payload = _valid_strategy_payload("X v. Y")
    assert_no_forbidden_phrases(json.dumps(payload))


def test_recommended_route_strategy_route_pydantic_rejects_extra() -> None:
    """``StrategyRoute`` is ``extra='forbid'`` — payloads with unknown
    keys must fail validation rather than silently passing them
    through to the persistence layer."""
    from pydantic import ValidationError

    with pytest.raises(ValidationError):
        StrategyRoute.model_validate(
            {
                "label": "valid label",
                "rationale": "valid rationale",
                "confidence": "low",
                "availability": "available",
                "supporting_citations": [],
                "risk_notes": None,
                "outcome_promised": "guaranteed",  # injected key
            }
        )


# ---------------------------------------------------------------
# Successful generation — happy path.
# ---------------------------------------------------------------


def test_strategy_generation_persists_review_required_with_payload(
    client: TestClient, mock_strategy_provider,
) -> None:
    token, _, matter_id = _setup_matter(client, forum_level="high_court")
    response = client.post(
        f"/api/matters/{matter_id}/recommendations",
        headers=auth_headers(token),
        json={"type": "litigation_strategy"},
    )
    assert response.status_code == 200, response.text
    body = response.json()
    assert body["type"] == "litigation_strategy"
    assert body["review_required"] is True
    assert body["status"] == "proposed"

    payload = body["strategy_payload"]
    assert payload is not None
    # LitigationStrategyPayload-validated shape, not a free-text blob.
    assert payload["recommended_route"]["label"]
    assert payload["forum_sequence"]
    assert payload["disclaimer"]
    # Recommended drafts list is hydrated from the registry — the
    # display_name + purpose fields come from the schema, not the LLM.
    assert payload["recommended_drafts"], (
        "Strategy payload should include a recommended-drafts panel."
    )
    for draft in payload["recommended_drafts"]:
        assert draft["template_type"]
        assert draft["display_name"]


def test_strategy_includes_escalation_forum_sequence(
    client: TestClient, mock_strategy_provider,
) -> None:
    """Escalation ladder must surface the SC step when an HC matter is
    in scope — that is the whole point of the planner."""
    token, _, matter_id = _setup_matter(client, forum_level="high_court")
    response = client.post(
        f"/api/matters/{matter_id}/recommendations",
        headers=auth_headers(token),
        json={"type": "litigation_strategy"},
    )
    assert response.status_code == 200
    forum_sequence = response.json()["strategy_payload"]["forum_sequence"]
    forum_levels = [step["forum_level"] for step in forum_sequence]
    assert "supreme_court" in forum_levels


def test_strategy_persists_with_audit_event(
    client: TestClient, mock_strategy_provider,
) -> None:
    token, _, matter_id = _setup_matter(client, forum_level="high_court")
    response = client.post(
        f"/api/matters/{matter_id}/recommendations",
        headers=auth_headers(token),
        json={"type": "litigation_strategy"},
    )
    assert response.status_code == 200
    rec_id = response.json()["id"]

    # Verify the persisted row + audit row.
    factory = get_session_factory()
    with factory() as session:
        rec = session.scalar(
            select(Recommendation).where(Recommendation.id == rec_id)
        )
        assert rec is not None
        assert rec.type == "litigation_strategy"
        assert rec.review_required is True
        assert rec.strategy_payload_json is not None
        # Round-trips through the Pydantic model.
        round_trip = LitigationStrategyPayload.model_validate(
            json.loads(rec.strategy_payload_json),
        )
        assert round_trip.recommended_route.label

        audit_events = list(
            session.scalars(
                select(AuditEvent).where(
                    AuditEvent.target_id == rec_id,
                    AuditEvent.action == "recommendation.generated",
                )
            )
        )
        assert audit_events, "Strategy generation must write an audit row."
        meta = json.loads(audit_events[0].metadata_json or "{}")
        assert meta.get("type") == "litigation_strategy"
        assert meta.get("forum_steps", 0) >= 1


# ---------------------------------------------------------------
# Refusal path — zero verified citations.
# ---------------------------------------------------------------


def test_strategy_refuses_when_no_citations_are_verified(
    client: TestClient, monkeypatch,
) -> None:
    """If the LLM returns citations that don't match any retrieved
    authority, the strategy is refused with HTTP 422 and the model_run
    is tagged ``rejected_no_verified_citations``."""
    from caseops_api.services.llm import LLMCompletion, LLMMessage

    _seed_relevant_authority()  # retrieval has SOMETHING to grab onto.

    payload = _valid_strategy_payload("Made Up v. Nobody (2099)")
    # Force the only citation to be unverifiable.
    payload["recommended_route"]["supporting_citations"] = [
        "Made Up v. Nobody (2099)",
    ]
    for alt in payload["alternative_routes"]:
        alt["supporting_citations"] = ["Made Up v. Nobody (2099)"]

    class _Hallucinator:
        name = "mock"
        model = "mock-hallucinate"

        def generate(self, messages: list[LLMMessage], **_kwargs):
            return LLMCompletion(
                text=json.dumps(payload),
                provider=self.name,
                model=self.model,
                prompt_tokens=10,
                completion_tokens=20,
                latency_ms=5,
            )

    monkeypatch.setattr(
        "caseops_api.services.recommendations.build_provider",
        lambda *a, **kw: _Hallucinator(),
    )
    monkeypatch.setattr(
        "caseops_api.services.litigation_strategy.build_provider",
        lambda *a, **kw: _Hallucinator(),
    )

    token, _, matter_id = _setup_matter(client, forum_level="high_court")
    response = client.post(
        f"/api/matters/{matter_id}/recommendations",
        headers=auth_headers(token),
        json={"type": "litigation_strategy"},
    )
    assert response.status_code == 422, response.text
    detail = response.json()["detail"]
    assert "verified" in detail.lower()
    assert "X-Model-Run-Id" in response.headers

    factory = get_session_factory()
    with factory() as session:
        runs = list(
            session.scalars(
                select(ModelRun).where(
                    ModelRun.purpose == "recommendation:litigation_strategy",
                )
            )
        )
    # Either ``rejected_primary_route_uncited`` (P1 #1, the per-route
    # gate that fires first when the primary has zero citations) OR
    # ``rejected_no_verified_citations`` (the original cross-route
    # total-zero gate) is a valid audit row for this case. Both are
    # correctness-preserving refusals — the test only requires that ONE
    # of them was persisted.
    assert any(
        r.status in {
            "rejected_no_verified_citations",
            "rejected_primary_route_uncited",
        }
        for r in runs
    ), "Refusal must be persisted as a ModelRun row for audit."


# ---------------------------------------------------------------
# Refusal path — forbidden phrase slipped through.
# ---------------------------------------------------------------


def test_strategy_refuses_when_forbidden_phrase_in_payload(
    client: TestClient, monkeypatch,
) -> None:
    """Even with verified citations, an output containing
    ``perfect strategy`` / ``will win`` / etc. must fail closed before
    persistence."""
    from caseops_api.services.llm import LLMCompletion, LLMMessage

    citation = _seed_relevant_authority()
    payload = _valid_strategy_payload(citation)
    # Slip a forbidden phrase into the rationale.
    payload["recommended_route"]["rationale"] = (
        "This is a perfect strategy that will win on the merits."
    )

    class _Bad:
        name = "mock"
        model = "mock-forbidden"

        def generate(self, messages: list[LLMMessage], **_kwargs):
            return LLMCompletion(
                text=json.dumps(payload),
                provider=self.name,
                model=self.model,
                prompt_tokens=10,
                completion_tokens=20,
                latency_ms=5,
            )

    monkeypatch.setattr(
        "caseops_api.services.recommendations.build_provider",
        lambda *a, **kw: _Bad(),
    )
    monkeypatch.setattr(
        "caseops_api.services.litigation_strategy.build_provider",
        lambda *a, **kw: _Bad(),
    )

    token, _, matter_id = _setup_matter(client, forum_level="high_court")
    response = client.post(
        f"/api/matters/{matter_id}/recommendations",
        headers=auth_headers(token),
        json={"type": "litigation_strategy"},
    )
    assert response.status_code == 422, response.text
    detail = response.json()["detail"].lower()
    assert "outcome" in detail or "disallow" in detail
    factory = get_session_factory()
    with factory() as session:
        runs = list(
            session.scalars(
                select(ModelRun).where(
                    ModelRun.purpose == "recommendation:litigation_strategy",
                )
            )
        )
    assert any(r.status == "rejected_forbidden_phrase" for r in runs), (
        "A forbidden-phrase refusal must persist as a ModelRun row."
    )


# ---------------------------------------------------------------
# Round-2 P1 #1: per-route citation verification on the PRIMARY.
# A primary route with zero verified citations must NOT be saved
# even if an alternative carries one verified citation.
# ---------------------------------------------------------------


def test_strategy_refuses_when_primary_route_uncited_even_if_alternative_cited(
    client: TestClient, monkeypatch,
) -> None:
    """If the recommended_route's only citation is unverifiable but an
    alternative_route's citation IS verified, the strategy must still
    refuse with 422 + ``rejected_primary_route_uncited``. The primary
    route is what the user reads first; we cannot lend it the support
    of an alternative."""
    from caseops_api.services.llm import LLMCompletion, LLMMessage

    citation = _seed_relevant_authority()  # alternative WILL match this.

    payload = _valid_strategy_payload(citation)
    # Primary route's only citation is unverifiable.
    payload["recommended_route"]["supporting_citations"] = [
        "Made Up v. Nobody (2099)",
    ]
    # Alternative carries the real, verifiable citation.
    payload["alternative_routes"][0]["supporting_citations"] = [
        f"[1] {citation}",
    ]

    class _PrimaryUncited:
        name = "mock"
        model = "mock-primary-uncited"

        def generate(self, messages: list[LLMMessage], **_kwargs):
            return LLMCompletion(
                text=json.dumps(payload),
                provider=self.name,
                model=self.model,
                prompt_tokens=10,
                completion_tokens=20,
                latency_ms=5,
            )

    monkeypatch.setattr(
        "caseops_api.services.recommendations.build_provider",
        lambda *a, **kw: _PrimaryUncited(),
    )
    monkeypatch.setattr(
        "caseops_api.services.litigation_strategy.build_provider",
        lambda *a, **kw: _PrimaryUncited(),
    )

    token, _, matter_id = _setup_matter(client, forum_level="high_court")
    response = client.post(
        f"/api/matters/{matter_id}/recommendations",
        headers=auth_headers(token),
        json={"type": "litigation_strategy"},
    )
    assert response.status_code == 422, response.text
    detail = response.json()["detail"]
    assert "primary" in detail.lower()
    assert "X-Model-Run-Id" in response.headers

    factory = get_session_factory()
    with factory() as session:
        runs = list(
            session.scalars(
                select(ModelRun).where(
                    ModelRun.purpose == "recommendation:litigation_strategy",
                )
            )
        )
    assert any(
        r.status == "rejected_primary_route_uncited" for r in runs
    ), (
        "Primary-route-uncited refusal must persist as a ModelRun row."
    )

    # Strategy must NOT have been persisted.
    factory = get_session_factory()
    with factory() as session:
        recs = list(
            session.scalars(
                select(Recommendation).where(
                    Recommendation.type == "litigation_strategy",
                )
            )
        )
    assert recs == [], "Strategy with uncited primary must not persist."


# ---------------------------------------------------------------
# SC-availability gate — drafts that are SC-only get marked
# unavailable on a non-SC matter.
# ---------------------------------------------------------------


def test_strategy_marks_sc_only_drafts_unavailable_on_lower_court_matter(
    client: TestClient, mock_strategy_provider,
) -> None:
    """A matter at the trial-court forum cannot file an SLP yet; the
    recommended-drafts panel must surface the SC pack as
    ``available=false`` with a reason."""
    token, _, matter_id = _setup_matter(client, forum_level="lower_court")
    response = client.post(
        f"/api/matters/{matter_id}/recommendations",
        headers=auth_headers(token),
        json={"type": "litigation_strategy"},
    )
    assert response.status_code == 200, response.text
    drafts = response.json()["strategy_payload"]["recommended_drafts"]
    sc_drafts = [
        d for d in drafts
        if d["template_type"] in {
            "special_leave_petition", "synopsis_list_of_dates",
            "condonation_of_delay",  # NOT SC-only — checks negative case
        }
    ]
    if sc_drafts:
        slp_entries = [d for d in sc_drafts if d["template_type"] == "special_leave_petition"]
        for entry in slp_entries:
            assert entry["available"] is False
            assert entry["reason_unavailable"]


# ---------------------------------------------------------------
# Tenant isolation — tenant A's strategy is invisible to tenant B.
# ---------------------------------------------------------------


def test_strategy_is_tenant_isolated(
    client: TestClient, mock_strategy_provider,
) -> None:
    # Tenant A creates a matter and generates a strategy.
    token_a, _, matter_id_a = _setup_matter(client, forum_level="high_court")
    response = client.post(
        f"/api/matters/{matter_id_a}/recommendations",
        headers=auth_headers(token_a),
        json={"type": "litigation_strategy"},
    )
    assert response.status_code == 200

    # Tenant B (independent bootstrap) reads the same matter id —
    # tenant isolation must 404.
    bootstrap_b = client.post(
        "/api/bootstrap/company",
        json={
            "company_name": "Other Firm LLP",
            "company_slug": "other-firm-litst",
            "company_type": "law_firm",
            "owner_full_name": "Other Owner",
            "owner_email": "owner@otherfirmlitst.in",
            "owner_password": "OtherFirm123!",
        },
    )
    assert bootstrap_b.status_code == 200, bootstrap_b.text
    token_b = str(bootstrap_b.json()["access_token"])
    other = client.get(
        f"/api/matters/{matter_id_a}/recommendations",
        headers=auth_headers(token_b),
    )
    assert other.status_code in (403, 404), other.text


# ---------------------------------------------------------------
# Recommendations capability gate — viewer-class roles cannot
# generate. (We assert the existing capability table covers
# litigation_strategy because dispatch goes through the same route.)
# ---------------------------------------------------------------


def test_unauthenticated_strategy_request_is_rejected(client: TestClient) -> None:
    """Unauthenticated request must NOT generate a strategy. The exact
    code is 401 (no auth) or 403 (capability check fails first); both
    are valid 'not authorized' outcomes."""
    response = client.post(
        "/api/matters/some-matter-id/recommendations",
        json={"type": "litigation_strategy"},
    )
    assert response.status_code in (401, 403), response.text
