export const siteConfig = {
  name: "CaseOps",
  tagline: "The matter-native legal operating system.",
  description:
    "CaseOps unifies legal intake and conflict clearance, matter management, notice and reply-deadline tracking, research, drafting, hearings, court-order compliance review, cause-list PDFs, contracts, outside counsel, and India-ready matter billing in one citation-grounded workspace for Indian legal teams.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://caseops.ai",
  appUrl: process.env.NEXT_PUBLIC_APP_URL ?? "https://caseops.ai/app",
  keywords: [
    "legal operating system",
    "legal software India",
    "law firm software",
    "matter management",
    "legal research platform",
    "AI legal drafting",
    "hearing preparation",
    "court order compliance",
    "case tracking India",
    "cause list PDF",
    "matter billing India",
    "GST invoice legal software",
    "contract review",
    "legal operations",
    "general counsel software",
    "litigation management",
    "outside counsel management",
    "Pine Labs UAT readiness",
    "legal AI India",
    "case management software",
  ],
  author: "CaseOps",
  twitter: "@caseops",
  locale: "en_IN",
  contact: {
    email: "mishra.sanjeev@gmail.com",
    sales: "mishra.sanjeev@gmail.com",
    support: "support@caseops.ai",
    founder: "mishra.sanjeev@gmail.com",
  },
  nav: {
    primary: [
      { label: "Product", href: "#product" },
      { label: "Pricing", href: "/pricing" },
      { label: "Law firms", href: "/law-firms" },
      { label: "General counsels", href: "/general-counsels" },
      { label: "Solo lawyers", href: "/solo-lawyers" },
      { label: "Guide", href: "/guide" },
    ],
    footer: {
      Product: [
        { label: "Matter Cockpit", href: "/#product" },
        { label: "Notices", href: "/#product" },
        { label: "Conflict checks", href: "/#product" },
        { label: "Research", href: "/#product" },
        { label: "Drafting Studio", href: "/#product" },
        { label: "Hearing Prep", href: "/#product" },
        { label: "Case tracking", href: "/#product" },
        { label: "Matter billing", href: "/#product" },
      ],
      Company: [
        { label: "For law firms", href: "/law-firms" },
        { label: "For general counsels", href: "/general-counsels" },
        { label: "For solo lawyers", href: "/solo-lawyers" },
        { label: "User guide", href: "/guide" },
        { label: "Contact", href: "mailto:mishra.sanjeev@gmail.com" },
      ],
      Trust: [
        { label: "Security", href: "/#security" },
        { label: "Multi-tenancy", href: "/#security" },
        { label: "AI governance", href: "/#security" },
      ],
    },
  },
} as const;

export type SiteConfig = typeof siteConfig;
