import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen } from "@testing-library/react";
import type { ReactNode } from "react";
import { beforeEach, describe, expect, it, vi } from "vitest";

const { fetchMock, historyMock, detailMock, createMock, capabilityMock } = vi.hoisted(() => ({ fetchMock: vi.fn(), historyMock: vi.fn(), detailMock: vi.fn(), createMock: vi.fn(), capabilityMock: vi.fn() }));
vi.mock("@/lib/api/endpoints", () => ({ fetchTenantDataGovernanceIntegrity: fetchMock, listTenantDataOperationDryRuns: historyMock, fetchTenantDataOperationDryRun: detailMock, createTenantDataOperationDryRun: createMock }));
vi.mock("@/lib/capabilities", () => ({ useCapability: () => capabilityMock() }));
import DataGovernancePage from "@/app/app/admin/data-governance/page";

function withClient(children: ReactNode) { return <QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}>{children}</QueryClientProvider>; }

describe("DataGovernancePage", () => {
  beforeEach(() => { capabilityMock.mockReset(); fetchMock.mockReset(); historyMock.mockReset(); detailMock.mockReset(); createMock.mockReset(); capabilityMock.mockReturnValue(true); fetchMock.mockResolvedValue({ checks: [{ check_id: "expired_unpurged", status: "unavailable", summary: "No approved schedule.", findings: [], blocked_by: "DATA-GOV-02" }], ok_count: 0, finding_count: 0, unavailable_count: 1, is_complete: false }); historyMock.mockResolvedValue({ operations: [{ id: "dry-run-1", operation_type: "tenant_export", execution_mode: "dry_run", status: "dry_run_complete", approval_status: "not_requested", rejection_reason: null, request_scope_hash: "scope-hash", manifest_hash: "manifest-hash", request_evidence_ref: "DATA-GOV-01", completed_at: "2026-08-20T00:00:00Z", as_of: "2026-08-20T00:00:00Z" }] }); detailMock.mockResolvedValue({ id: "dry-run-1", operation_type: "tenant_export", execution_mode: "dry_run", status: "dry_run_complete", approval_status: "not_requested", rejection_reason: null, request_scope_hash: "scope-hash", manifest_hash: "manifest-hash", request_evidence_ref: "DATA-GOV-01", completed_at: "2026-08-20T00:00:00Z", as_of: "2026-08-20T00:00:00Z", items: [], exclusions: [], offboarding_plan: [], dependency_plan: null }); createMock.mockResolvedValue({ id: "dry-run-created", operation_type: "tenant_export", execution_mode: "dry_run", status: "dry_run_complete", approval_status: "not_requested", rejection_reason: null, request_scope_hash: "scope-hash", manifest_hash: "manifest-hash", request_evidence_ref: "DATA-GOV-01", completed_at: "2026-08-20T00:00:00Z", as_of: "2026-08-20T00:00:00Z", items: [], exclusions: [], offboarding_plan: [], dependency_plan: null }); });
  it("shows unavailable controls as unavailable, not healthy", async () => { render(withClient(<DataGovernancePage />)); expect(await screen.findByTestId("governance-check-expired_unpurged")).toHaveTextContent("unavailable"); expect(screen.getByText("Blocked by: DATA-GOV-02")).toBeInTheDocument(); expect(screen.getByText(/cannot approve, export, purge/i)).toBeInTheDocument(); });
  it("does not fetch for a non-owner", () => { capabilityMock.mockReturnValue(false); render(withClient(<DataGovernancePage />)); expect(screen.getByText(/Workspace owner required/i)).toBeInTheDocument(); expect(fetchMock).not.toHaveBeenCalled(); });
  it("reviews a selected dry-run manifest without exposing an operation control", async () => { render(withClient(<DataGovernancePage />)); fireEvent.click(await screen.findByTestId("dry-run-dry-run-1")); expect(await screen.findByText("manifest-hash")).toBeInTheDocument(); expect(screen.getByText(/not an execution authorization/i)).toBeInTheDocument(); expect(detailMock).toHaveBeenCalledWith("dry-run-1"); });
  it("creates only a hashed-input non-executable dry run", async () => { render(withClient(<DataGovernancePage />)); fireEvent.change(screen.getByLabelText(/Evidence reference/i), { target: { value: "ticket://review" } }); fireEvent.change(screen.getByLabelText(/Registered data class ID/i), { target: { value: "legal_holds" } }); fireEvent.change(screen.getByLabelText(/Target type/i), { target: { value: "tenant" } }); fireEvent.change(screen.getByLabelText(/SHA-256 target reference/i), { target: { value: "a".repeat(64) } }); fireEvent.click(screen.getByRole("button", { name: /Create non-executable dry run/i })); await screen.findByTestId("dry-run-detail"); expect(createMock).toHaveBeenCalledWith(expect.objectContaining({ operationType: "tenant_export", requestEvidenceRef: "ticket://review", items: [expect.objectContaining({ dataClassId: "legal_holds", targetReferenceHash: "a".repeat(64) })] })); expect(screen.getByText(/do not enter client, matter, or document identifiers/i)).toBeInTheDocument(); });
});
