"""P1-001 (2026-04-24, QG-* coverage gates) — coverage gate.

Reads ``coverage.json`` (generated by pytest-cov ``--cov-report=json``)
and fails CI when:

  * a tracked module drops below its per-file baseline, OR
  * a tracked package (`api`, `core`, `db`, `schemas`, `services`)
    drops below its per-bucket line/branch baseline (AQ-001 ratchet),
    OR
  * the totals drop below the overall line/branch baseline.

Per-file checks are the most surgical (security-critical paths). Per-
bucket and totals are the AQ-001 ratchet — the audit asked for
ratcheting thresholds by area, not just on 9 critical files, plus a
total floor so a wholesale coverage collapse fails CI even if no
single file crosses its per-file gate. Update an entry only when the
underlying module/bucket has gained real test coverage; never ratchet
a threshold DOWN to make a flaky CI green.

Usage:
    pytest --cov=caseops_api --cov-report=json:coverage.json
    python scripts/coverage_gate.py [coverage.json]

Exit 0 = all gates pass. Exit 1 = at least one gate failed.
"""
from __future__ import annotations

import collections
import json
import sys
from pathlib import Path

# Module -> (minimum coverage %, last_measured %, date+commit)
# When you raise coverage on a module, update the threshold AND the
# last-measured % so future drops are obvious in the diff.
THRESHOLDS: dict[str, tuple[float, float, str]] = {
    # Security-critical core (must stay high)
    "src/caseops_api/core/cookies.py": (88.0, 91.0, "2026-04-24 89bf4b3"),
    "src/caseops_api/core/csrf.py": (95.0, 100.0, "2026-04-24 89bf4b3"),
    "src/caseops_api/core/security.py": (80.0, 87.0, "2026-04-24 89bf4b3"),
    "src/caseops_api/core/settings.py": (90.0, 95.0, "2026-04-24 89bf4b3"),
    "src/caseops_api/core/problem_details.py": (88.0, 92.0, "2026-04-24 15084ee"),
    # Audit / portal / file security
    "src/caseops_api/services/audit.py": (90.0, 96.0, "2026-04-24 89bf4b3"),
    "src/caseops_api/services/file_security.py": (88.0, 95.0, "2026-04-24 550a4be"),
    "src/caseops_api/services/portal_auth.py": (75.0, 82.0, "2026-04-24 e7c8fb7"),
    "src/caseops_api/services/virus_scan.py": (85.0, 90.0, "2026-04-24 89bf4b3"),
}

# AQ-001 (2026-04-25) — per-bucket ratchet. Each bucket = first dir
# under src/caseops_api/. Floors are set ~0.5–2.0 pts under the
# 2026-04-25 baseline so flaky test exclusion doesn't break the gate
# but a real coverage regression in a bucket trips it. Branch floor is
# `None` where the bucket has no branches (e.g. pure schemas).
# Tuple: (min_line%, min_branch% or None, last_measured_line%,
#         last_measured_branch%, anchor).
BUCKET_THRESHOLDS: dict[str, tuple[float, float | None, float, float, str]] = {
    "api": (70.0, 28.0, 71.6, 29.6, "2026-04-25 729b7e1"),
    "core": (82.0, 60.0, 83.3, 63.2, "2026-04-25 729b7e1"),
    "db": (98.0, 68.0, 99.4, 70.0, "2026-04-25 729b7e1"),
    "schemas": (98.0, None, 99.5, 0.0, "2026-04-25 729b7e1"),
    "services": (25.0, 6.0, 25.8, 7.1, "2026-04-25 729b7e1"),
}

# AQ-001 — overall totals floor. Headroom under the 2026-04-25
# baseline (line 41.54%, branch 9.99%). Raise these as broad coverage
# improves; never lower them to make CI green.
TOTAL_LINE_MIN = 41.0
TOTAL_BRANCH_MIN = 9.5
TOTAL_LAST_MEASURED = "line 41.54%, branch 9.99% — 2026-04-25 729b7e1"


def _normalise(path: str) -> str:
    """coverage.json uses OS-native separators; we compare against
    POSIX paths in THRESHOLDS so the gate is portable."""
    return path.replace("\\", "/").lstrip("./")


def main() -> int:
    report_path = Path(sys.argv[1] if len(sys.argv) >= 2 else "coverage.json")
    if not report_path.exists():
        print(
            f"::error::coverage gate cannot find {report_path}. "
            "Run pytest with --cov-report=json:coverage.json first.",
            file=sys.stderr,
        )
        return 1

    data = json.loads(report_path.read_text(encoding="utf-8"))
    files = data.get("files", {})
    if not files:
        print("::error::coverage.json has no per-file data.", file=sys.stderr)
        return 1

    by_path = {_normalise(k): v for k, v in files.items()}

    failures: list[str] = []
    for module, (minimum, baseline, anchor) in THRESHOLDS.items():
        module_norm = _normalise(module)
        # Some pytest-cov configurations strip the leading "src/" off
        # the report keys (when run with --cov=src/...). Try both.
        candidate_keys = [
            module_norm,
            module_norm.removeprefix("src/"),
            "apps/api/" + module_norm,
        ]
        entry = next(
            (by_path[k] for k in candidate_keys if k in by_path),
            None,
        )
        if entry is None:
            failures.append(
                f"{module}: not found in coverage report (tried {candidate_keys})"
            )
            continue
        summary = entry.get("summary", {})
        percent = float(summary.get("percent_covered", 0.0))
        if percent < minimum:
            failures.append(
                f"{module}: {percent:.1f}% < required {minimum:.1f}% "
                f"(was {baseline:.1f}% at {anchor})"
            )
        else:
            print(
                f"OK {module}: {percent:.1f}% (>= {minimum:.1f}%, baseline "
                f"{baseline:.1f}%)"
            )

    # AQ-001: per-bucket ratchet (groups files under src/caseops_api/<bucket>/).
    bucket_stats: dict[str, dict[str, int]] = collections.defaultdict(
        lambda: {"cov": 0, "stmt": 0, "br_cov": 0, "br_tot": 0}
    )
    for path, entry in by_path.items():
        rel = path.removeprefix("apps/api/").removeprefix(
            "src/caseops_api/"
        )
        if "/" not in rel:
            continue  # _root files, skip
        bucket = rel.split("/", 1)[0]
        s = entry.get("summary", {})
        bucket_stats[bucket]["cov"] += int(s.get("covered_lines", 0))
        bucket_stats[bucket]["stmt"] += int(s.get("num_statements", 0))
        bucket_stats[bucket]["br_cov"] += int(s.get("covered_branches", 0))
        bucket_stats[bucket]["br_tot"] += int(s.get("num_branches", 0))

    for bucket, (
        line_min,
        branch_min,
        line_baseline,
        branch_baseline,
        anchor,
    ) in BUCKET_THRESHOLDS.items():
        v = bucket_stats.get(bucket)
        if not v or v["stmt"] == 0:
            failures.append(
                f"bucket {bucket}: no files seen in coverage report"
            )
            continue
        line_pct = v["cov"] / v["stmt"] * 100
        if line_pct < line_min:
            failures.append(
                f"bucket {bucket} line: {line_pct:.1f}% < required "
                f"{line_min:.1f}% (was {line_baseline:.1f}% at {anchor})"
            )
        else:
            print(
                f"OK bucket {bucket} line: {line_pct:.1f}% "
                f"(>= {line_min:.1f}%, baseline {line_baseline:.1f}%)"
            )
        if branch_min is not None and v["br_tot"] > 0:
            br_pct = v["br_cov"] / v["br_tot"] * 100
            if br_pct < branch_min:
                failures.append(
                    f"bucket {bucket} branch: {br_pct:.1f}% < required "
                    f"{branch_min:.1f}% (was {branch_baseline:.1f}% at {anchor})"
                )
            else:
                print(
                    f"OK bucket {bucket} branch: {br_pct:.1f}% "
                    f"(>= {branch_min:.1f}%, baseline {branch_baseline:.1f}%)"
                )

    # AQ-001: overall totals floor.
    totals = data.get("totals", {})
    total_line = float(totals.get("percent_covered", 0.0))
    total_branch = float(totals.get("percent_branches_covered", 0.0))
    if total_line < TOTAL_LINE_MIN:
        failures.append(
            f"TOTAL line: {total_line:.2f}% < required {TOTAL_LINE_MIN:.2f}% "
            f"({TOTAL_LAST_MEASURED})"
        )
    else:
        print(
            f"OK TOTAL line: {total_line:.2f}% (>= {TOTAL_LINE_MIN:.2f}%)"
        )
    if total_branch < TOTAL_BRANCH_MIN:
        failures.append(
            f"TOTAL branch: {total_branch:.2f}% < required "
            f"{TOTAL_BRANCH_MIN:.2f}% ({TOTAL_LAST_MEASURED})"
        )
    else:
        print(
            f"OK TOTAL branch: {total_branch:.2f}% "
            f"(>= {TOTAL_BRANCH_MIN:.2f}%)"
        )

    if failures:
        print("::error::Coverage gate FAILED:", file=sys.stderr)
        for f in failures:
            print(f"  - {f}", file=sys.stderr)
        print(
            "\nIf the drop is intentional (e.g. you removed dead code), "
            "lower the THRESHOLDS / BUCKET_THRESHOLDS / TOTAL_*_MIN entry "
            "in scripts/coverage_gate.py and explain in the commit message.",
            file=sys.stderr,
        )
        return 1

    print(
        f"\nAll {len(THRESHOLDS)} per-file + {len(BUCKET_THRESHOLDS)} "
        "per-bucket + 2 total coverage gates passed."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
