"""P1-001 (2026-04-24, QG-* coverage gates) — per-area coverage gate.

Reads ``coverage.json`` (generated by pytest-cov ``--cov-report=json``)
and fails CI when any tracked module drops below its baseline.

The audit asks for "targeted per-area gates before attempting a blunt
global threshold." The dict below is the source of truth: each entry
captures the baseline %% measured 2026-04-24. Update an entry only
when the underlying module has gained genuine test coverage; never
ratchet a threshold DOWN to make a flaky CI green.

Usage:
    pytest --cov=caseops_api --cov-report=json:coverage.json
    python scripts/coverage_gate.py [coverage.json]

Exit 0 = all gates pass. Exit 1 = at least one gate failed; output
lists the regressed files with current vs required %.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

# Module -> (minimum coverage %, last_measured %, date+commit)
# When you raise coverage on a module, update the threshold AND the
# last-measured % so future drops are obvious in the diff.
THRESHOLDS: dict[str, tuple[float, float, str]] = {
    # Security-critical core (must stay high)
    "src/caseops_api/core/cookies.py": (88.0, 91.0, "2026-04-24 89bf4b3"),
    "src/caseops_api/core/csrf.py": (95.0, 100.0, "2026-04-24 89bf4b3"),
    "src/caseops_api/core/security.py": (80.0, 87.0, "2026-04-24 89bf4b3"),
    "src/caseops_api/core/settings.py": (90.0, 95.0, "2026-04-24 89bf4b3"),
    "src/caseops_api/core/problem_details.py": (88.0, 92.0, "2026-04-24 15084ee"),
    # Audit / portal / file security
    "src/caseops_api/services/audit.py": (90.0, 96.0, "2026-04-24 89bf4b3"),
    "src/caseops_api/services/file_security.py": (88.0, 95.0, "2026-04-24 550a4be"),
    "src/caseops_api/services/portal_auth.py": (75.0, 82.0, "2026-04-24 e7c8fb7"),
    "src/caseops_api/services/virus_scan.py": (85.0, 90.0, "2026-04-24 89bf4b3"),
}


def _normalise(path: str) -> str:
    """coverage.json uses OS-native separators; we compare against
    POSIX paths in THRESHOLDS so the gate is portable."""
    return path.replace("\\", "/").lstrip("./")


def main() -> int:
    report_path = Path(sys.argv[1] if len(sys.argv) >= 2 else "coverage.json")
    if not report_path.exists():
        print(
            f"::error::coverage gate cannot find {report_path}. "
            "Run pytest with --cov-report=json:coverage.json first.",
            file=sys.stderr,
        )
        return 1

    data = json.loads(report_path.read_text(encoding="utf-8"))
    files = data.get("files", {})
    if not files:
        print("::error::coverage.json has no per-file data.", file=sys.stderr)
        return 1

    by_path = {_normalise(k): v for k, v in files.items()}

    failures: list[str] = []
    for module, (minimum, baseline, anchor) in THRESHOLDS.items():
        module_norm = _normalise(module)
        # Some pytest-cov configurations strip the leading "src/" off
        # the report keys (when run with --cov=src/...). Try both.
        candidate_keys = [
            module_norm,
            module_norm.removeprefix("src/"),
            "apps/api/" + module_norm,
        ]
        entry = next(
            (by_path[k] for k in candidate_keys if k in by_path),
            None,
        )
        if entry is None:
            failures.append(
                f"{module}: not found in coverage report (tried {candidate_keys})"
            )
            continue
        summary = entry.get("summary", {})
        percent = float(summary.get("percent_covered", 0.0))
        if percent < minimum:
            failures.append(
                f"{module}: {percent:.1f}% < required {minimum:.1f}% "
                f"(was {baseline:.1f}% at {anchor})"
            )
        else:
            print(
                f"OK {module}: {percent:.1f}% (>= {minimum:.1f}%, baseline "
                f"{baseline:.1f}%)"
            )

    if failures:
        print("::error::Coverage gate FAILED:", file=sys.stderr)
        for f in failures:
            print(f"  - {f}", file=sys.stderr)
        print(
            "\nIf the drop is intentional (e.g. you removed dead code), "
            "lower the THRESHOLDS entry in scripts/coverage_gate.py and "
            "explain in the commit message.",
            file=sys.stderr,
        )
        return 1

    print(f"\nAll {len(THRESHOLDS)} coverage gates passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
