"""Compiled runtime projection of the reviewed data-class registries.

GENERATED FILE - DO NOT EDIT.

Regenerate with, in this order:

    python scripts/ip_data_governance_map.py generate
    python scripts/ip_data_class_projection.py render
    python scripts/ip_data_governance_map.py render

``scripts/ip_data_class_projection.py validate`` runs in CI and fails if this
file is not byte-identical to what ``render`` produces from the reviewed
artifacts, so hand-edits do not survive review.

This module exists because ``apps/api/Dockerfile`` ships ``src`` and not
``docs``: the reviewed YAML is unreadable in production, so it is compiled into
the package that does ship.
"""

from __future__ import annotations

from caseops_api.governance.types import ReviewedDataClass

PROJECTION_SCHEMA_VERSION = 1

# Fingerprints of the exact artifacts this projection was rendered from.
MAP_DOCUMENT_FINGERPRINT = "355e22888164e0af099910f13f8fc1dfa8369eb57ccdb2b27e904411b6ee00d2"
MAP_SCHEMA_FINGERPRINT = "6694174e27af162ccd5de701c02885b6e69dbe2589de69e16355a0c33244b489"
REGISTRY_028A_FINGERPRINT = "dd3c30cf69a9b498cea3820acb485a0368a72bf6d9348c2f0d430b5efa99802d"
REGISTRY_027A_FINGERPRINT = "10b97a818b23d4fae8fe7f54b63edb50b0e04c16778cf0e646ef907f40e1ad96"
# The ORM schema at render time. Compared against the live models at runtime, so
# an image whose models moved after this file was rendered reports stale rather
# than answering from a projection that no longer describes it.
ORM_SCHEMA_FINGERPRINT = "93f36a7be8936613ae7ffaaed32bd1bbd670a350e458f15ec44bc6d729c6e8fa"

PROJECTION_ID = "2b060938599677fd713a5dabdf4a6763d35f01941eaab1fbfc84eaafa63b25bd"

# Every SQL table the repository-wide map inventories. Membership here is what
# separates "inventoried but never reviewed" from "no such data class", which
# are different answers with different remedies.
INVENTORIED_SQL_TABLES = frozenset(
    {
        "account_setup_tokens",
        "affidavit_intelligence_runs",
        "affidavit_questions",
        "affidavit_statements",
        "agent_executions",
        "agent_grants",
        "agent_tool_calls",
        "ai_feedback_items",
        "ai_governance_approvals",
        "api_idempotency_records",
        "assistant_action_previews",
        "assistant_citations",
        "assistant_session_scopes",
        "assistant_sessions",
        "assistant_turns",
        "audit_events",
        "audit_export_jobs",
        "authority_annotations",
        "authority_citations",
        "authority_document_chunks",
        "authority_documents",
        "authority_ingestion_runs",
        "authority_research_report_sources",
        "authority_research_reports",
        "authority_search_observations",
        "authority_statute_references",
        "bench_aliases",
        "benches",
        "billing_accounts",
        "billing_admin_notes",
        "billing_chargeback_disputes",
        "billing_checkout_sessions",
        "billing_coupon_redemptions",
        "billing_coupons",
        "billing_credit_ledger",
        "billing_credit_notes",
        "billing_enrollments",
        "billing_manual_invoices",
        "billing_margin_simulations",
        "billing_overage_policies",
        "billing_payment_orders",
        "billing_plan_entitlements",
        "billing_plan_prices",
        "billing_plan_versions",
        "billing_profit_rollups",
        "billing_provider_events",
        "billing_provider_fee_reconciliations",
        "billing_reconciliation_exceptions",
        "billing_refund_records",
        "billing_settlement_imports",
        "billing_settlement_rows",
        "billing_subscription_items",
        "billing_subscriptions",
        "billing_tds_reconciliation_rows",
        "billing_usage_attribution",
        "billing_usage_events",
        "billing_usage_rollups",
        "bulk_import_jobs",
        "calendar_event_candidates",
        "calendar_event_syncs",
        "calendar_projection_reconciliation_candidates",
        "case_tracking_support_matrix",
        "cause_list_exports",
        "clients",
        "communications",
        "companies",
        "company_ip_rule_policies",
        "company_memberships",
        "company_notice_ip_links",
        "company_notice_matter_links",
        "company_notices",
        "connector_health_records",
        "connector_secret_rotation_evidence",
        "contract_activity",
        "contract_attachment_chunks",
        "contract_attachments",
        "contract_clauses",
        "contract_legal_references",
        "contract_obligations",
        "contract_playbook_rules",
        "contract_term_suggestions",
        "contracts",
        "courts",
        "custom_roles",
        "data_retention_policies",
        "data_retention_versions",
        "document_processing_jobs",
        "domain_consumer_effects",
        "domain_outbox_events",
        "draft_reviews",
        "draft_versions",
        "drafting_data_extraction_fields",
        "drafts",
        "drive_file_candidates",
        "drive_sync_controls",
        "email_calendar_candidates",
        "email_suppressions",
        "email_templates",
        "employee_bulk_import_jobs",
        "employee_bulk_import_rows",
        "employee_profiles",
        "ethical_walls",
        "evaluation_cases",
        "evaluation_runs",
        "forum_catalog_entries",
        "hearing_pack_items",
        "hearing_packs",
        "hearing_reminder_delivery_intents",
        "hearing_reminders",
        "in_app_notifications",
        "inbound_email_aliases",
        "inbound_email_events",
        "ip_assets",
        "ip_client_instructions",
        "ip_control_review_exception_decisions",
        "ip_control_review_sample_evidence",
        "ip_control_review_signatures",
        "ip_cost_item_corrections",
        "ip_cost_items",
        "ip_deadline_coverages",
        "ip_deadline_incident_actions",
        "ip_deadline_incident_impacts",
        "ip_deadline_incident_notification_decisions",
        "ip_deadline_incidents",
        "ip_deadlines",
        "ip_docket_control_reviews",
        "ip_docket_events",
        "ip_docket_queues",
        "ip_docket_records",
        "ip_document_links",
        "ip_document_taxonomy_aliases",
        "ip_document_taxonomy_entries",
        "ip_document_versions",
        "ip_documents",
        "ip_evidence_candidates",
        "ip_foreign_associate_instructions",
        "ip_identifiers",
        "ip_import_rows",
        "ip_incident_kill_switches",
        "ip_journal_ingestion_runs",
        "ip_journal_publications",
        "ip_matter_links",
        "ip_parties_and_roles",
        "ip_portfolio_export_jobs",
        "ip_portfolio_saved_views",
        "ip_post_registration_recordals",
        "ip_proceedings",
        "ip_registry_diffs",
        "ip_registry_links",
        "ip_registry_snapshots",
        "ip_registry_sync_attempts",
        "ip_related_right_obligations",
        "ip_relationships",
        "ip_renewal_terms",
        "ip_responsibility_assignments",
        "ip_rule_sets",
        "ip_rule_versions",
        "ip_title_interests",
        "ip_tracked_case_links",
        "ip_trademark_particular_versions",
        "ip_watch_handoffs",
        "ip_watch_hits",
        "ip_watch_profiles",
        "ip_workflow_definitions",
        "ip_workflow_versions",
        "ip_workspace_configurations",
        "ip_workspace_test_results",
        "judge_aliases",
        "judge_appointments",
        "judge_authority_affinity",
        "judge_decision_index",
        "judge_mapping_reviews",
        "judge_statute_focus",
        "judges",
        "judgment_alert_rules",
        "judgment_alerts",
        "legal_hold_items",
        "legal_holds",
        "legal_knowledge_graph_edges",
        "legal_knowledge_graph_nodes",
        "legal_knowledge_graph_runs",
        "legal_update_alerts",
        "legal_update_source_records",
        "legal_update_source_runs",
        "legal_update_watchlists",
        "legal_working_calendar_versions",
        "legal_working_calendars",
        "litigation_intelligence_review_actions",
        "mailbox_attachment_candidates",
        "mailbox_message_imports",
        "mailbox_webhook_events",
        "matter_access_grants",
        "matter_activity",
        "matter_attachment_annotations",
        "matter_attachment_chunks",
        "matter_attachments",
        "matter_billing_profiles",
        "matter_billing_rates",
        "matter_bulk_import_jobs",
        "matter_bulk_import_rows",
        "matter_cause_list_entries",
        "matter_client_assignments",
        "matter_compliance_extraction_runs",
        "matter_compliance_items",
        "matter_conflict_checks",
        "matter_court_orders",
        "matter_court_sync_jobs",
        "matter_court_sync_runs",
        "matter_deadlines",
        "matter_file_qa_entries",
        "matter_hearings",
        "matter_intake_requests",
        "matter_invoice_exports",
        "matter_invoice_line_items",
        "matter_invoice_payment_attempts",
        "matter_invoices",
        "matter_next_hearing_history",
        "matter_next_hearing_suggestions",
        "matter_notes",
        "matter_outside_counsel_assignments",
        "matter_portal_grants",
        "matter_proceeding_signals",
        "matter_statute_references",
        "matter_strategy_entries",
        "matter_tag_assignments",
        "matter_tags",
        "matter_tasks",
        "matter_time_entries",
        "matters",
        "mock_hearing_questions",
        "mock_hearing_responses",
        "mock_hearing_sessions",
        "model_runs",
        "notification_delivery_events",
        "notification_delivery_intents",
        "notification_rules",
        "outside_counsel",
        "outside_counsel_spend_records",
        "payment_webhook_events",
        "pine_labs_production_activation_decisions",
        "pine_labs_uat_runs",
        "pine_labs_uat_scenario_evidence",
        "platform_admin_audit_events",
        "platform_admin_memberships",
        "platform_operational_readiness_evidence",
        "portal_magic_links",
        "portal_publication_targets",
        "portal_publications",
        "portal_users",
        "predictive_outcome_aggregate_snapshots",
        "predictive_outcome_classifications",
        "predictive_signal_evidence",
        "predictive_signal_items",
        "predictive_signal_runs",
        "private_index_generations",
        "private_index_projection_scopes",
        "private_index_projections",
        "private_projection_events",
        "private_saved_output_access",
        "production_billing_signoff_evidence",
        "production_billing_signoffs",
        "provider_cost_profiles",
        "recommendation_decisions",
        "recommendation_options",
        "recommendations",
        "report_artifacts",
        "source_link_reports",
        "statute_change_events",
        "statute_sections",
        "statute_source_conflicts",
        "statute_source_versions",
        "statutes",
        "team_memberships",
        "teams",
        "tenant_ai_policies",
        "tenant_contract_playbook_rules",
        "tenant_contract_playbooks",
        "tenant_data_operation_items",
        "tenant_data_operations",
        "tenant_enterprise_identity_configurations",
        "tenant_google_workspace_configurations",
        "tenant_microsoft365_configurations",
        "tenant_notification_preferences",
        "tenant_outlook_configurations",
        "tenant_security_policies",
        "tracked_case_bookmarks",
        "tracked_case_poll_runs",
        "tracked_case_provider_operations",
        "tracked_case_provider_snapshots",
        "tracked_case_updates",
        "tracked_cases",
        "trademark_application_scopes",
        "trademark_applications",
        "trademark_international_registrations",
        "trademark_representations",
        "user_calendar_connections",
        "user_drive_connections",
        "user_mailbox_connections",
        "user_mfa_recovery_codes",
        "user_mfa_settings",
        "user_mfa_step_ups",
        "user_notification_preferences",
        "users",
        "voyage_usage",
    }
)

# Object stores, indexes, caches, queues, logs, provider-held records. Kept in a
# SEPARATE set and never merged: they have no table, so a dependency plan cannot
# be computed for them, and folding them in would let one be requested as though
# it could be purged relationally.
INVENTORIED_NON_SQL_CLASSES = frozenset(
    {
        "application-logs-traces-and-metrics",
        "audit-export-artifacts",
        "authority-document-pgvector-index",
        "connector-and-payment-provider-held-records",
        "database-and-object-backups",
        "database-queues-outbox-and-dead-letter",
        "document-materialization-cache",
        "document-object-prefix-and-version",
        "llm-and-embedding-provider-held-content",
        "matter-attachment-pgvector-index",
        "sql-relational-index-projections",
        "tenant-private-retrieval-candidate-cache",
    }
)

# Reviewed by IPLF-028A and admissible in a dry run.
ADMITTED_DATA_CLASSES: dict[str, ReviewedDataClass] = {
    "data_retention_policies": ReviewedDataClass(
        id="data_retention_policies",
        table_name="data_retention_policies",
        source_slice="IPLF-028A",
        company_scope="required",
        company_key="company_id",
        storage="migration_managed_relational_table",
        confidentiality="confidential",
        legal_hold_disposition="hold-aware-handler-unimplemented",
    ),
    "data_retention_versions": ReviewedDataClass(
        id="data_retention_versions",
        table_name="data_retention_versions",
        source_slice="IPLF-028A",
        company_scope="required",
        company_key="company_id",
        storage="migration_managed_relational_table",
        confidentiality="confidential",
        legal_hold_disposition="hold-aware-handler-unimplemented",
    ),
    "legal_hold_items": ReviewedDataClass(
        id="legal_hold_items",
        table_name="legal_hold_items",
        source_slice="IPLF-028A",
        company_scope="required",
        company_key="company_id",
        storage="migration_managed_relational_table",
        confidentiality="privileged",
        legal_hold_disposition="authoritative-preservation-scope",
    ),
    "legal_holds": ReviewedDataClass(
        id="legal_holds",
        table_name="legal_holds",
        source_slice="IPLF-028A",
        company_scope="required",
        company_key="company_id",
        storage="migration_managed_relational_table",
        confidentiality="privileged",
        legal_hold_disposition="authoritative-preservation-state",
    ),
    "tenant_data_operation_items": ReviewedDataClass(
        id="tenant_data_operation_items",
        table_name="tenant_data_operation_items",
        source_slice="IPLF-028A",
        company_scope="required",
        company_key="company_id",
        storage="migration_managed_relational_table",
        confidentiality="privileged",
        legal_hold_disposition="held-item-requires-hold-evidence",
    ),
    "tenant_data_operations": ReviewedDataClass(
        id="tenant_data_operations",
        table_name="tenant_data_operations",
        source_slice="IPLF-028A",
        company_scope="required",
        company_key="company_id",
        storage="migration_managed_relational_table",
        confidentiality="privileged",
        legal_hold_disposition="active-hold-conservatively-suppresses-dry-run-targets",
    ),
}

# Reviewed by IPLF-027A, which governs its own tables. Present so a caller
# naming one is told it is governed elsewhere rather than "never reviewed".
REVIEWED_ELSEWHERE_DATA_CLASSES: dict[str, ReviewedDataClass] = {
    "api_idempotency_records": ReviewedDataClass(
        id="api_idempotency_records",
        table_name="api_idempotency_records",
        source_slice="IPLF-027A",
        company_scope="required",
        company_key="company_id",
        storage="migration_managed_relational_table",
        confidentiality="confidential",
        legal_hold_disposition=(
            "Preserve matching company, actor, operation, and stable result-reference "
            "evidence when a later approved hold handler covers it."
        ),
    ),
    "domain_consumer_effects": ReviewedDataClass(
        id="domain_consumer_effects",
        table_name="domain_consumer_effects",
        source_slice="IPLF-027A",
        company_scope="required",
        company_key="company_id",
        storage="migration_managed_relational_table",
        confidentiality="confidential",
        legal_hold_disposition=(
            "Preserve consumer-effect evidence when its company, source event, "
            "aggregate, or data class is held by a later approved policy."
        ),
    ),
    "domain_outbox_events": ReviewedDataClass(
        id="domain_outbox_events",
        table_name="domain_outbox_events",
        source_slice="IPLF-027A",
        company_scope="required",
        company_key="company_id",
        storage="migration_managed_relational_table",
        confidentiality="privileged",
        legal_hold_disposition=(
            "Preserve current and future events matching the held "
            "company/aggregate/data-class scope once the IPLF-028 handler exists."
        ),
    ),
    "ip_workflow_definitions": ReviewedDataClass(
        id="ip_workflow_definitions",
        table_name="ip_workflow_definitions",
        source_slice="IPLF-027A",
        company_scope="required",
        company_key="company_id",
        storage="migration_managed_relational_table",
        confidentiality="confidential",
        legal_hold_disposition=(
            "Preserve matching company workflow definitions and future versions once a "
            "later approved hold handler covers them."
        ),
    ),
    "ip_workflow_versions": ReviewedDataClass(
        id="ip_workflow_versions",
        table_name="ip_workflow_versions",
        source_slice="IPLF-027A",
        company_scope="required",
        company_key="company_id",
        storage="migration_managed_relational_table",
        confidentiality="privileged",
        legal_hold_disposition=(
            "Preserve matching current and future version evidence when the company, "
            "workflow, docket, source, or data class is held by a later approved "
            "policy."
        ),
    ),
}
